# Generated by Django 5.2.13 on 2026-05-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lecture_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='source_language',
            field=models.CharField(default='gu', max_length=10),
        ),
    ]
